### ISSUE TITLE
why "Loading checkpoint shards:"  take me so long time

### ISSUE THREAD

**Issue by xueqing0622** [kijai/ComfyUI-KwaiKolorsWrapper#6]
whait is  "Loading checkpoint shards:", why "Loading checkpoint shards:"  take me so long time
![image](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/assets/114840118/660956bf-db5b-4f06-b37e-b4cde9f9f702)

**Comment by kijai** [comment]
How much memory do you have? VRAM and RAM? And if you monitor them at that stage, does it get full?

**Comment by xueqing0622** [comment]
VRAM 3060Ti 12G
RAM 32G

**Comment by xueqing0622** [comment]
![image](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/assets/114840118/0fdbfcae-7a81-4da4-a9a1-fccf608b7cd7)

**Comment by kijai** [comment]
I added loading from safetensors now, but it needs re-download, I don't know if it would help with this at all though.

**Comment by xueqing0622** [comment]
yes, very quickly now, the 8G only 1 second now。 thx very much
